#!/usr/bin/env node
// EERI — carry the PALETTE and the per-world GROUND COLOUR across to Godot.
//
// CLAUDE.md: **content is authored once and flows; code is not shared.** Six
// pipelines already run that way — levels, scenery, strings, glyphs, audio,
// assets — and none of them has ever drifted, because regenerating is the
// only way to change one. Colour was the last thing still being retyped, and
// on 2026-09-07 the retyped copies were measured against each other:
//
//     pipeworks lip   js/level.js  mix(GREEN, STEEL[2], 0.30)
//                     play.gd      mix(GREEN, STEEL[2], 0.20)
//     nightshift lip  js/level.js  mix(mix(GREEN, INK, 0.48), SKY, 0.12)
//                     play.gd      mix(GREEN, INK, 0.45)        ← no sky at all
//     grove earth     js/level.js  mix(E[1], GREEN_DK, 0.22), mix(E[2], …, 0.38)
//                     play.gd      mix(E[1], GREEN_DK, 0.12), mix(E[2], …, 0.28)
//
// Nobody decided that the forest floor should be a different green in the two
// builds. Somebody typed a number twice. Those are not stylistic differences
// a port is allowed — the whole point of the per-world earth was that four
// worlds stopped reading as the same place, and half of that work never
// reached the tablet.
//
// WHAT IT EMITS, and why it is RESOLVED rather than symbolic:
//
//     data/palette.json
//       { pal: { SKY: "#4aa8e8", EARTH: [...], … },
//         layerZ: {...}, layerTint: {...},
//         ground: { groundworks: { earth: [4 hex], lip: hex, fringe: hex }, … } }
//
// The mixes are EVALUATED here. A port that re-evaluated `mix(a, b, 0.3)`
// would be a second implementation of the rule, which is the thing the rule
// forbids — and it is how the numbers above came to disagree in the first
// place. The port reads finished colours and cannot express an opinion.
//
// Run:  node tools/export-palette.mjs
//       node tools/export-palette.mjs --check    (fail if data/ has drifted)
import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', 'data');
const CHECK = process.argv.includes('--check');

// NOTHING IMPORTED HERE MAY REACH `three`. That is not a style note: the
// tables this tool exists for lived in `js/level.js`, which imports `three`
// on its first line, and Node cannot resolve a bare specifier without the
// browser's import map — so for four worlds they were literally unreadable by
// any tool. `js/ground.js` was split out to fix exactly that, and adding an
// import below that pulls in the painter would silently undo it.
const { PAL, LAYER_Z, LAYER_TINT } = await import(new URL('../../js/palette.js', import.meta.url));
const { GROUND_WORLDS, groundPalette } = await import(new URL('../../js/ground.js', import.meta.url));

const ground = {};
for (const w of GROUND_WORLDS) ground[w] = groundPalette(w);

const payload = {
  _readme: 'GENERATED by godot/tools/export-palette.mjs from js/palette.js and js/ground.js — do not hand-edit.',
  pal: PAL,
  layerZ: LAYER_Z,
  layerTint: LAYER_TINT,
  ground,
};

const body = JSON.stringify(payload, null, 2);
const file = join(OUT, 'palette.json');

if (CHECK) {
  if (!existsSync(file)) {
    console.error('FAIL: data/palette.json is missing');
    process.exit(1);
  }
  if (readFileSync(file, 'utf8') !== body) {
    console.error('FAIL: data/palette.json has drifted from js/palette.js + js/ground.js');
    process.exit(1);
  }
  console.log(`OK: data/palette.json matches — ${GROUND_WORLDS.length} world(s)`);
} else {
  mkdirSync(OUT, { recursive: true });
  writeFileSync(file, body);
  console.log(`Wrote data/palette.json — ${Object.keys(PAL).length} palette entries, ${GROUND_WORLDS.length} worlds`);
  for (const w of GROUND_WORLDS) {
    const g = ground[w];
    console.log(`  ${w.padEnd(12)} earth ${g.earth.join(' ')}   lip ${g.lip}   fringe ${g.fringe}`);
  }
}
