#!/usr/bin/env node
// EERI — compile the authored rooms into data Godot can read.
//
// The levels are CODE, not data: js/rooms.js declares each room as a list of
// parts and js/parts.js compiles them into a tile grid plus entity lists.
// There is no JSON level format to import, so this makes one — by running the
// real compiler, never by hand-transcribing it.
//
// That distinction is the whole point. A hand-copied level is a second source
// of truth that drifts silently; a generated one cannot, because re-running
// this is the only way to change it. It is the same rule sync-data.mjs
// follows for the art manifest, and the reason `data/` is git-ignored.
//
// Writes:  godot/data/levels/<slug>.json   (one per authored room)
//          godot/data/levels/index.json    (the ordered roster + tile legend)
//
// Run:  node tools/export-levels.mjs
//       node tools/export-levels.mjs --check    (fail if data/ has drifted)

import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..');
const OUT = join(HERE, '..', 'data', 'levels');
const CHECK = process.argv.includes('--check');

const { ROOMS } = await import(new URL('../../js/rooms.js', import.meta.url));
const { WORLD34_ROOMS } = await import(new URL('../../js/world34-rooms.js', import.meta.url));
const PARTS = await import(new URL('../../js/parts.js', import.meta.url));
const { slugOf } = await import(new URL('../../js/levelid.js', import.meta.url));

// The runtime roster, not the static one. js/world34-register.js pushes
// worlds 3 and 4 on at RUNTIME — test/rooms.mjs was proving six of twelve
// levels and reporting green because it imported only the static list. Take
// the same roster the game takes.
const ROOMS_ALL = [...ROOMS, ...WORLD34_ROOMS];

function exportRoom(def, i) {
  const c = PARTS.compile(def);
  // grid is row 0 = TOP. Keep it exactly as the compiler emits it and let the
  // Godot side do the one flip, in one place, rather than flipping here and
  // again there — two flips that disagree is a level upside down.
  return {
    index: i,
    slug: slugOf(i),
    name: c.name,
    idea: c.idea ?? null,
    w: PARTS.W,
    h: PARTS.H,
    ground: PARTS.GROUND,
    // one string per row: compact, diffable, and trivially indexable in GDScript
    grid: c.grid.map((row) => row.join('')),
    spawn: c.spawn,
    exit: c.exit,
    checkpoint: c.checkpoint ?? null,
    flag: c.flag ?? null,
    bolts: c.bolts,
    golden: c.golden,
    blueprint: c.blueprint ?? null,
    pits: c.pits,
    ladders: c.ladders,
    belts: c.belts,
    tarps: c.tarps,
    water: c.water,
    pipes: c.pipes,
    hoists: c.hoists,
    robots: c.robots,
    hazards: c.hazards,
    machines: c.machines,
    obstacles: c.obstacles,
    shots: c.shots,
  };
}

const levels = ROOMS_ALL.map(exportRoom);
const index = {
  _readme: 'GENERATED by godot/tools/export-levels.mjs from js/rooms.js — do not hand-edit.',
  count: levels.length,
  // The legend the Godot collision needs. Taken from parts.js rather than
  // restated, because a second copy of "what counts as solid" is a second
  // physics model.
  solid: PARTS.SOLID_CHARS,
  climb: PARTS.CLIMB_CHAR ?? '=',
  levels: levels.map((l) => ({ index: l.index, slug: l.slug, name: l.name, file: `${l.slug}.json` })),
};

const files = new Map([['index.json', JSON.stringify(index, null, 2)]]);
for (const l of levels) files.set(`${l.slug}.json`, JSON.stringify(l, null, 2));

if (CHECK) {
  const problems = [];
  for (const [name, body] of files) {
    const p = join(OUT, name);
    if (!existsSync(p)) problems.push(`data/levels/${name} is missing`);
    else if (readFileSync(p, 'utf8') !== body) problems.push(`data/levels/${name} has drifted from js/rooms.js`);
  }
  if (problems.length) {
    console.error(`FAIL: ${problems.length} problem(s)`);
    for (const p of problems) console.error(`  - ${p}`);
    process.exit(1);
  }
  console.log(`OK: ${levels.length} level(s) in data/levels/ match js/rooms.js`);
} else {
  mkdirSync(OUT, { recursive: true });
  for (const [name, body] of files) writeFileSync(join(OUT, name), body);
  console.log(`Wrote ${levels.length} level(s) + index.json into godot/data/levels/`);
  for (const l of levels) console.log(`  ${l.slug.padEnd(10)} ${l.name}`);
}
