class_name LevelData
extends RefCounted
## One authored room, loaded from data/levels/<slug>.json.
##
## The JSON is GENERATED by godot/tools/export-levels.mjs, which runs the real
## js/parts.js compiler over js/rooms.js. Nothing here re-authors level
## content, and nothing should: a hand-edited copy is a second source of truth
## that drifts in silence.
##
## COLLISION LIVES HERE, and it is a literal port of js/level.js's
## axis-separated AABB sweep — deliberately NOT Godot physics. DESIGN.md §4
## fixes a proved reach budget (apex 2.65 tiles, run-jump 4.85 across, no
## pixel-precision jumps) and test/rooms.mjs proves all twelve rooms against
## those exact numbers. A solver-dependent, frame-dependent CharacterBody3D
## would quietly stop those guarantees meaning anything, and the failure mode
## is a jump a six-year-old cannot make in a room the prover called fine.

const EPS := 0.001

var index := 0
var slug := ""
var display_name := ""
var w := 0
var h := 0
var ground := 0
## The tile legend, from js/parts.js. These are not decoration: every gizmo
## except the hoist and the pipe is "what is under your boot", which is why
## they cost almost nothing to implement and why getting a character wrong
## silently removes a whole mechanic from a level.
var solid_chars := "#=GBKCcT~"
var climb_char := "H"          # CLIMB_CHAR
var belt_chars := "Cc"         # BELT_CHARS: 'C' carries right, 'c' left
var tarp_char := "T"           # TARP_CHAR
var water_char := "~"          # WATER_CHAR

## grid[row] with row 0 = TOP, exactly as the compiler emits it. The single
## flip to world space happens in cell(), in one place — two flips that
## disagree is a level upside down.
var grid: PackedStringArray = PackedStringArray()

var spawn := {}
var exit_at := {}
var bolts: Array = []
var golden: Array = []
var ladders: Array = []
var pits: Array = []
var robots: Array = []
var hazards: Array = []
var machines: Array = []
var belts: Array = []
var tarps: Array = []
var water: Array = []
var pipes: Array = []
var hoists: Array = []
## Authored camera zones — a room's own framing (js/camera.js). Not
## decoration: "a lock you cannot see is not a lock".
var shots: Array = []
var bank = null
var flag = null
var blueprint = null
var wall = null
var girder = null
var gate = null
var checkpoint = null


static func load_index() -> Dictionary:
	var p := "res://data/levels/index.json"
	if not FileAccess.file_exists(p):
		push_error("missing %s — run: node tools/export-levels.mjs" % p)
		return {}
	var f := FileAccess.open(p, FileAccess.READ)
	var t := f.get_as_text()
	f.close()
	var parsed = JSON.parse_string(t)
	return parsed if typeof(parsed) == TYPE_DICTIONARY else {}


static func load_slug(want_slug: String) -> LevelData:
	var idx := load_index()
	if idx.is_empty():
		return null
	var p := "res://data/levels/%s.json" % want_slug
	if not FileAccess.file_exists(p):
		push_error("no such level: %s" % want_slug)
		return null
	var f := FileAccess.open(p, FileAccess.READ)
	var raw = JSON.parse_string(f.get_as_text())
	f.close()
	if typeof(raw) != TYPE_DICTIONARY:
		return null

	var d := LevelData.new()
	d.index = int(raw.get("index", 0))
	d.slug = String(raw.get("slug", want_slug))
	d.display_name = String(raw.get("name", ""))
	d.w = int(raw.get("w", 0))
	d.h = int(raw.get("h", 0))
	d.ground = int(raw.get("ground", 0))
	d.solid_chars = String(idx.get("solid", d.solid_chars))
	d.climb_char = String(idx.get("climb", d.climb_char))
	for row in raw.get("grid", []):
		d.grid.append(String(row))
	d.spawn = raw.get("spawn", {})
	d.exit_at = raw.get("exit", {})
	d.bolts = raw.get("bolts", [])
	d.golden = raw.get("golden", [])
	d.ladders = raw.get("ladders", [])
	d.pits = raw.get("pits", [])
	d.robots = raw.get("robots", [])
	d.bank = raw.get("bank", null)
	d.flag = raw.get("flag", null)
	d.blueprint = raw.get("blueprint", null)
	d.wall = raw.get("wall", null)
	d.girder = raw.get("girder", null)
	d.gate = raw.get("gate", null)
	d.hazards = raw.get("hazards", [])
	d.machines = raw.get("machines", [])
	d.belts = raw.get("belts", [])
	d.tarps = raw.get("tarps", [])
	d.water = raw.get("water", [])
	d.pipes = raw.get("pipes", [])
	d.hoists = raw.get("hoists", [])
	d.shots = raw.get("shots", [])
	d.checkpoint = raw.get("checkpoint", null)
	return d


## The character at tile (column, row-from-BOTTOM). This is the one place the
## grid's top-down storage is flipped to the game's bottom-up world space.
func cell(c: int, r: int) -> String:
	if c < 0 or c >= w or r < 0 or r >= h:
		return " "
	var line := grid[h - 1 - r]
	if c >= line.length():
		return " "
	return line[c]


func solid_cell(c: int, r: int) -> bool:
	# Out of bounds sideways is solid, so the room has walls rather than an
	# edge you walk off into nothing. Out of bounds vertically is not: falling
	# out of the world is a real state the respawn handles.
	if c < 0 or c >= w:
		return true
	if r < 0 or r >= h:
		return false
	return solid_chars.contains(cell(c, r))


## What is under the boot. Literal port of js/level.js underfoot() — note the
## 0.05 bias, which is what makes "standing on" read one tile down rather
## than the tile the feet are nominally inside.
func underfoot(x: float, y: float) -> String:
	return cell(int(floor(x)), int(floor(y - 0.05)))


func climb_at(x: float, y: float) -> bool:
	return cell(int(floor(x)), int(floor(y))) == climb_char


## +1 carries right, -1 left, 0 for no belt.
func belt_at(x: float, y: float) -> int:
	var ch := underfoot(x, y)
	if not belt_chars.contains(ch):
		return 0
	return 1 if ch == "C" else -1


func tarp_at(x: float, y: float) -> bool:
	return underfoot(x, y) == tarp_char


## Shallow water: a floor that slows you (DESIGN world 2).
func water_at(x: float, y: float) -> bool:
	return underfoot(x, y) == water_char


## Top of the climbable run in this column, or null-ish (-1) if none.
## Literal port of js/level.js climbTop().
func climb_top(x: float, y: float) -> float:
	var c := int(floor(x))
	var top := -1
	var start: int = max(0, int(floor(y)) - 1)
	for cy in range(start, h):
		if cell(c, cy) == climb_char:
			top = cy
		elif top != -1:
			break
	return -1.0 if top == -1 else float(top + 1)


# ---- the sweep. box = {x: centre, y: feet, hw, h} ------------------------
# Speeds stay well under a tile per step, so single-cell checks hold — the
# same assumption js/level.js states and relies on.

func move_x(bx: float, by: float, hw: float, bh: float, dx: float) -> Dictionary:
	if dx == 0.0:
		return {"x": bx, "hit": false}
	var s := signf(dx)
	var nx := bx + dx
	var edge := nx + s * hw
	var c := int(floor(edge))
	var sy := by + 0.02
	while sy < by + bh:
		if solid_cell(c, int(floor(min(sy, by + bh - 0.02)))):
			nx = (c - hw - EPS) if s > 0 else (c + 1 + hw + EPS)
			return {"x": nx, "hit": true}
		sy += 0.9
	return {"x": nx, "hit": false}


func move_y(bx: float, by: float, hw: float, bh: float, dy: float) -> Dictionary:
	if dy == 0.0:
		return {"y": by, "hit": false, "grounded": false}
	var ny := by + dy
	if dy < 0.0:
		var row := int(floor(ny))
		var sx := bx - hw + 0.02
		while sx < bx + hw:
			if solid_cell(int(floor(min(sx, bx + hw - 0.02))), row):
				return {"y": float(row + 1), "hit": true, "grounded": true}
			sx += 0.9
		return {"y": ny, "hit": false, "grounded": false}
	var row_up := int(floor(ny + bh))
	var sx2 := bx - hw + 0.02
	while sx2 < bx + hw:
		if solid_cell(int(floor(min(sx2, bx + hw - 0.02))), row_up):
			return {"y": float(row_up) - bh - EPS, "hit": true, "grounded": false}
		sx2 += 0.9
	return {"y": ny, "hit": false, "grounded": false}


func is_grounded(bx: float, by: float, hw: float) -> bool:
	var row := int(floor(by - 0.05))
	var sx := bx - hw + 0.02
	while sx < bx + hw:
		if solid_cell(int(floor(min(sx, bx + hw - 0.02))), row):
			return true
		sx += 0.9
	return false


## The map is a FACT, and digging or seating changes it. Both edit the same
## stored grid, so collision, the room prover's view and what is drawn can
## never disagree about whether the way is open.
func clear_row(cc0: int, cc1: int, cy: int) -> void:
	_set_row(cc0, cc1, cy, " ")


func fill_row(cc0: int, cc1: int, cy: int, ch := "G") -> void:
	_set_row(cc0, cc1, cy, ch)


func _set_row(cc0: int, cc1: int, cy: int, ch: String) -> void:
	var r := h - 1 - cy
	if r < 0 or r >= grid.size():
		return
	var line := grid[r]
	for c in range(maxi(cc0, 0), mini(cc1, w - 1) + 1):
		line = line.substr(0, c) + ch + line.substr(c + 1)
	grid[r] = line


## A RUNG IS NOT SOLID IN ANY DIRECTION — you walk through it, fall through
## it, and only the climb verb holds you on it. A solid ladder is a wall with
## a picture of a ladder on it. The two samples are the feet and the chest, so
## standing at the foot of one is enough to start.
func climbable(x: float, y: float) -> bool:
	var c := int(floor(x))
	if c < 0 or c >= w:
		return false
	for sy in [y + 0.1, y + 0.8]:
		if cell(c, int(floor(sy))) == climb_char:
			return true
	return false


## Top of the first solid at or below y in this column. Literal port of
## js/level.js groundTop() — the robots' floor and the blob shadow's ground.
## Returns -4 over a pit: deliberately below the world, so a robot that walks
## off its span falls out of frame rather than hovering.
func ground_top(x: float, y_from: float) -> float:
	var c := int(floor(x))
	var cy := int(floor(y_from - EPS))
	while cy >= 0:
		if solid_cell(c, cy):
			return float(cy + 1)
		cy -= 1
	return -4.0


## Fell past the floor. Literal port of js/level.js fallRespawn(): the near
## side of whichever pit took you, else the last checkpoint, never the start —
## a level is 60-90 seconds and losing all of it to one hole is the cost this
## game promised never to charge (DESIGN §4).
func fall_respawn(x: float, last_checkpoint = null) -> Vector2:
	for p in pits:
		var c0 := float(p.get("c0", 0))
		var c1 := float(p.get("c1", 0))
		if x > c0 - 1.0 and x < c1 + 2.0:
			return Vector2(float(p.get("backX", c0 - 2.0)), 5.0)
	if last_checkpoint != null:
		return Vector2(float(last_checkpoint.x), float(last_checkpoint.y) + 1.0)
	var k = spawn.get("kid", {})
	return Vector2(float(k.get("x", 4.5)), float(k.get("y", 4)) + 1.0)
